config/routes.rb
Rails.application.routes.draw do


	devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: "register"}

	controller :pages do
		get '/home' => :home
		get '/profile' => :profile
	end

	root "pages#home"  
	get '*path' => redirect('/')

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  # Define your fields
  # field :host, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	protect_from_forgery with: :exception
	before_action :store_user_location!, if: :storable_location?
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	

	rescue_from CanCan::AccessDenied do |exception|
		flash[:alert] = "Você não tem permissão para acessar!"
		redirect_back(fallback_location: root_url)
	end

	private

	def record_not_found
		flash[:alert] = "Você está tentando acessar algo que não existe."
		redirect_back(fallback_location: root_url)
	end

	def storable_location?
		request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
	end

	def store_user_location!
	  # :user is the scope we are authenticating
	  store_location_for(:user, request.fullpath)
	end

  def after_sign_out_path_for(resource_or_scope)
  	stored_location_for(resource_or_scope) || super
  end

end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
	before_action :authenticate_user!
	layout 'komodo'
	

	def home

	end

	def profile
		@user = current_user
	end

	private

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes"></head>
  </head>

  <body class="<%= controller_name %> <%= action_name %> public">

    <main>
      <%= yield %>
    </main>

    <footer>
      <%= render "/shared/footer" %>
    </footer>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'red'})" %>
      <% elsif message_type == 'notice' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'green'})" %>
      <% elsif message_type == 'danger' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'orange'})" %>
      <% elsif message_type == 'info' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'blue'})" %>
      <% end %>
    <% end %>
  </body>
</html>

app/views/layouts/komodo.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'komodo', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'komodo', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= favicon_link_tag '/favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes"></head>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

  <div id="current_user" user="<%= current_user.id %>"></div>
  
    <header class="header">
      <%= render "/shared/navbar" %>
    </header>

    <main class="animated <%= params[:page].blank? ? 'fadeIn' : 'fadeIn' %> faster">
      <%= yield %>
    </main>

    <footer>
      <%= render "/shared/footer" %>
    </footer>

    <div id="modal" class="modal">
    </div>
    <div id="dialog">
    </div>

    <% flash.each do |message_type, message| %>
      <% if message_type == 'alert' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'red'})" %>
      <% elsif message_type == 'notice' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'green'})" %>
      <% elsif message_type == 'danger' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'orange'})" %>
      <% elsif message_type == 'info' %>
        <%= javascript_tag "M.toast({html: '#{message}', classes: 'blue'})" %>
      <% end %>
    <% end %>


  </body>
</html>

app/views/pages/home.html.erb
<h5>Home</h5>

app/views/shared/_navbar.html.erb
<nav class="hide-on-large-only fixed">
  <div class="nav-wrapper">
    <a data-target="slide-out" class="sidenav-trigger"><i class="material-icons white-text">menu</i></a>
    <a href="/atendimento/home" class="animated flip margin-right-15 f12 peso-5 right cursor ajax_logo " data-tooltip="Visualizar atualizações"><i class="material-icons white-text">exit_to_app</i></a>

      <a href="/" class="margin-10 padding-10 f12 peso-5">Home</a>
  </div>
</nav>
<div class="height-64px hide-on-large-only"></div>



<ul id="slide-out" class="sidenav sidenav-fixed ">
  <li class="center">
    <img id="" src="/images/logo.png" class="ajax_logo img-fluid animated flip padding-10">
  </li>
  <li><%= link_to "<i class='material-icons #{'menu-icon' if current_page?home_path}'>home</i> <span class='hide-on-large-only'>Home</span>".html_safe, home_path, class: "tooltipped", 'data-tooltip' => "Home", "data-position" =>"right" %></li>

  <hr>
	<li><%= link_to "<i class='material-icons #{'menu-icon' if current_page?profile_path}'>person</i> <span class='hide-on-large-only'>Perfil</span>".html_safe, profile_path, class: "tooltipped", 'data-tooltip' => "Perfil", "data-position" =>"right" %></li>
	<li><%= link_to "<i class='material-icons #{'menu-icon' if current_page?destroy_user_session_path}'>exit_to_app</i> <span class='hide-on-large-only'>Sair</span>".html_safe, destroy_user_session_path, class: "tooltipped", 'data-tooltip' => "Sair", :method => :delete, "data-position" =>"right" %></li>
</ul>


<div class="height-64px hide-on-small-only"></div>
<nav id="shortcut" class="grey hide-on-small-only fixed top-0">
  <div class="nav-wrapper">
    <div class="row">
      <div class="col s12 m12 l11">
          <a href="/" class="margin-10 padding-10 f12 peso-5">Home</a>
          <a href="/atendimento/home" class=" animated flip delay-300 margin-right-15 f12 peso-5 right hide-on-small-only tooltipped" data-tooltip="Área de Atendimento"><i class="material-icons white-text">exit_to_app</i></a>
          <a href="<%= request.env['PATH_INFO'] %>" class=" animated rotateIn margin-right-15 f12 peso-5 right hide-on-small-only cursor tooltipped" data-tooltip="Atualizar"><i class="material-icons white-text">refresh</i></a>
      </div>
    </div>
  </div>
</nav>